# Generated by Django 3.2.7 on 2021-11-23 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=30)),
                ('detalle_ejercicio', models.TextField(max_length=150)),
                ('fecha_ejercicio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('a_paterno', models.CharField(max_length=15)),
                ('a_materno', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(max_length=300)),
                ('completado', models.CharField(max_length=1)),
                ('evidencia', models.FileField(upload_to='video')),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ejercicio')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Kinesiologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('a_paterno', models.CharField(max_length=15)),
                ('a_materno', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('a_paterno', models.CharField(max_length=15)),
                ('a_materno', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ciudad')),
                ('id_kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.kinesiologo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='id_kinesiologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.kinesiologo'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.paciente'),
        ),
    ]
