# Generated by Django 3.2.7 on 2021-12-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='tipo_usuario',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='tipo_usuario',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_usuario',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
