# Generated by Django 3.2.7 on 2022-01-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20220130_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinesiologo',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
