# Generated by Django 4.0.5 on 2022-07-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20220201_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='kinesiologo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
