# Generated by Django 3.2.7 on 2021-12-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20211220_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='kinesiologo',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_usuario',
        ),
    ]
