# Generated by Django 3.2.7 on 2022-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20220130_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='kinesiologo',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
