# Generated by Django 3.2.7 on 2021-12-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipo_usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipo_usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipo_usuario'),
            preserve_default=False,
        ),
    ]
