# Generated by Django 3.2.7 on 2021-12-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20211220_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='user',
            new_name='userD',
        ),
        migrations.RenameField(
            model_name='kinesiologo',
            old_name='user',
            new_name='userD',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='user',
            new_name='userD',
        ),
    ]
