# Generated by Django 3.2.7 on 2021-12-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20211221_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='kinesiologo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo_Usuario',
        ),
    ]
